### ISSUE TITLE
Please help me to get acceleration.

### ISSUE THREAD

**Issue by PomPomiie** [jlsirois/VANETProject#6]
Hello Joanne.
I received the issue when I try to run the code. Omnet++ inform me for the acceleration then I check in the Inet framework version 3.6.7 and I found it close but when I open it, it errors in another file. 
However, I ever try to use other net framework versions like 4.2.0 but it's not working because there are many different paths. And, when I check inside it, there have not some the .ned file with version 3.6.7.
So, please kindly to guide me to pass this stage.

**Comment by chaotictoejam** [comment]
I am currently in the process of updating this project to work with the latest versions of INET and VEINS. This should be completed by this weekend. Lots of issues could be related to the fact that INET has had many breaking changes since this project was done. After this update, I will be more than happy to help you with acceleration, if it is still an issue.

**Comment by PomPomiie** [comment]
Thank you and appreciate you trying to help me.
